language: java
jdk:
  - oraclejdk8
before_install:
    # Download & execute last Redis version.
  - wget -P target/test-classes/ http://download.redis.io/releases/redis-stable.tar.gz
  - tar -xvf  target/test-classes/redis-stable.tar.gz -C target/test-classes/
  - rm target/test-classes/redis-stable.tar.gz
  - cd target/test-classes/redis-stable
  - make
  - cd ../../../
  - nohup target/test-classes/redis-stable/src/redis-server ./tools/Redis/test/redis.conf &
script:
  - mvn verify -X -f ./pom.xml
  - mvn package
  - mvn javadoc:javadoc
  - mvn clean site
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/cobertura/coverage.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN 
  - mvn versions:display-dependency-updates
  - mvn versions:display-plugin-updates
after_success:
  - sudo chmod +x ./travis-ci/bintray/upload.sh
  - ./travis-ci/bintray/upload.sh
